#!/bin/bash

'''
Example Command Line Input:
	./MasterNT.sh
	
Set of manual commands to run subscripts Trans_Novo.py and NTSubmission.sh on SLURM cluster.
'''
CURRENT_DIR="./"

mkdir $CURRENT_DIR/Data/out/
mkdir $CURRENT_DIR/Data/err/

sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=AMYB $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=AP-1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/ut.%j -e ./err/err.%j --export=ONE=Ap4 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Arnt:Ahr $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Ascl1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Atf1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Atf2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Atf3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Atf4 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Atf7 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Atoh1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Bach1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Bach2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Bapx1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Barx1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=BATF $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=BHLHA15 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=bHLHE40 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=bHLHE41 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=BMAL1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=BMYB $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=BORIS $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Brn1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Brn2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=bZIP:IRF $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=c-Jun-CRE $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=c-Myc $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=c-Myc $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=CArG $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Cdx2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=CDX4 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=CEBP $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Chop $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=CLOCK $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=COUP-TFII $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=COUP-TFII $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=CRE $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=CRX $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=CTCF-SatelliteElement $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=CTCF $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=CUX1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Cux2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Dlx3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Duxbl $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=E-box $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=E2F3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=E2F6 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=EAR2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Egr1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Egr2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Erra $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ERRg $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Esrrb $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Fosl2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Fox:Ebox $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Foxa2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Foxa3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=FoxD3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Foxf1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=FOXK1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=FOXK2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=FoxL2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=FOXM1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Foxo1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Foxo3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=FOXP1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Fra1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Fra2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=FXR $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=GATA:SCL $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Gfi1b $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=GFX $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=GFY-Staf $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=GSC $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Hand2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=HIF-1b $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=HIF2a $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=HLF $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=HNF4a $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=HNF6 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Hnf6b $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=HOXA1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Hoxa10 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Hoxa11 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Hoxa13 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=HOXA2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Hoxa9 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=HOXB13 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Hoxb4 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Hoxc9 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Hoxd10 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Hoxd11 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Hoxd12 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Hoxd13 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=HRE $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=HRE $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=IRF1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=IRF2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=IRF8 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Isl1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ISRE $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Jun-AP1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=JunB $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=JunD $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=KLF10 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=KLF14 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=KLF3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Klf4 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=KLF5 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=KLF6 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Klf9 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=LEF1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Lhx1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Lhx2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Lhx3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=LXH9 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=LXRE $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=MafA $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=MafB $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Max $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Maz $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Meis1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=MITF $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=MNT $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=MYB $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=MyoD $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=n-Myc $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Nanog $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=NeuroD1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=NeuroG2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=NF-E2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=NF1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=NFE2L2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=NFIL3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=NFY $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Nkx3.1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Nkx6.1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=NPAS $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=NPAS2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Nrf2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Nur77 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=OCT:OCT $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Oct11 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Oct2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=OCT4-SOX2-TCF-NANOG $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Oct4:Sox17 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Oct4 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Oct6 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Olig2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Otx2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=PAX3:FKHR-fusion $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=PAX5 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=PAX5 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=PAX6 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Pax8 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=PBX2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Pbx3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Pdx1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Phox2a $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Pit1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Pitx1:Ebox $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Pitx1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Pknox1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=PPARa $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=PPARE $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=PR $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=PRDM1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=PRDM14 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Prop1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=PU.1-IRF $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=PU.1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=RAR:RXR $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=RARa $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=RBPJ:Ebox $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Rbpj1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=REST-NRSF $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Reverb $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=RFX $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Rfx1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Rfx2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Rfx5 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=RORa $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=RORg $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=RORgt $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=RUNX2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=RXR $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=SCL $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Six1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Six2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Six4 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Smad2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Smad3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Smad4 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Sox10 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Sox15 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Sox17 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Sox2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Sox3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Sox4 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Sox6 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Sox9 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Sp1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Sp2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Sp5 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=SpiB $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Srebp1a $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Srebp2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=STAT1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=TATA-Box $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Tbet $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Tbx20 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Tcf12 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Tcf21 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Tcf3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=TCF4 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Tcf7 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=TEAD $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=TEAD1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=TEAD2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=TEAD3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=TEAD4 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=TFE3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Tgif1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Tgif2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=THRa $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=THRb $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=TR4 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Twist2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Unknown-ESC-element $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Unknown $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=USF1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Usf2 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=VDR $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=WT1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=X-box $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=YY1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Zac1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ZBTB18 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Zfp281 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Zic $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Zic3 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ZKSCAN1 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ZNF189 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=Znf263 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ZNF382 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ZNF41 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ZNF467 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ZNF519 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ZNF669 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ZNF675 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ZNF692 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ZNF7 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ZNF768 $CURRENT_DIR/Subscripts/TN_Submission.sh
sbatch --job-name=TRANSNOVO -o ./out/out.%j -e ./err/err.%j --export=ONE=ZSCAN22 $CURRENT_DIR/Subscripts/TN_Submission.sh
